---
patient_id:
  type: 'String'
  required: true
  help: 'Patient identifier'
dataset_id:
  type: 'String'
  required: true
  help: 'Dataset identifier'
algorithm:
  type: 'List'
  required: true
  help: 'List of QC algorithms'
  choices:
    - fastqc
    - stats
    - depth
    - collectwgsmetrics
    - bamqc
reference:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to reference fasta'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
blcds_registered_dataset:
  type: 'Bool'
  required: false
  default: false
  help: 'if you want the output to be registered (Boutros Lab only)'
save_intermediate_files:
  type: 'Bool'
  required: false
  default: false
  help: 'The option to save the intermediate files'
fastqc_level:
  type: 'String'
  required: true
  help: 'FastQC level of analysis'
  choices:
    - readgroup
    - library
    - sample
  default:
    - sample
fastqc_additional_options:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for FastQC command'
stats_max_rgs_per_sample:
  type: 'Integer'
  required: false
  default: 20
  help: 'Maximum number of read groups to process separately'
stats_max_libs_per_sample:
  type: 'Integer'
  required: false
  default: 20
  help: 'Maximum number of libraries to process separately'
stats_remove_duplicates:
  type: 'Bool'
  required: false
  default: false
  help: 'SAMtools stats option to remove duplicates'
stats_additional_options:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for SAMtools stats command'
depth_output_all_positions:
  type: 'Bool'
  required: false
  default: false
  help: 'Output all positions (including those with zero depth)'
depth_minimum_base_quality:
  type: 'Integer'
  required: false
  default: 0
  help: 'Minimum base quality for depth calculation'
depth_minimum_mapping_quality:
  type: 'Integer'
  required: false
  default: 0
  help: 'Minimum mapping quality for depth calculation'
depth_single_count_overlaps:
  type: 'Bool'
  required: false
  default: false
  help: 'Count overlapping reads only once'
depth_include_deletion_reads:
  type: 'Bool'
  required: false
  default: false
  help: 'Include reads with deletions in depth calculation'
depth_additional_options:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for depth command'
cwm_coverage_cap:
  type: 'Integer'
  required: false
  default: 250
  help: 'Coverage cap for CollectWgsMetrics'
cwm_minimum_mapping_quality:
  type: 'Integer'
  required: false
  default: 20
  help: 'Minimum mapping quality for CollectWgsMetrics'
cwm_minimum_base_quality:
  type: 'Integer'
  required: false
  default: 20
  help: 'Minimum base quality for CollectWgsMetrics'
cwm_use_fast_algorithm:
  type: 'Bool'
  required: false
  default: false
  help: 'Use fast algorithm for CollectWgsMetrics'
cwm_additional_options:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for CollectWgsMetrics command'
bamqc_output_format:
  type: 'String'
  required: false
  choices:
    - html
    - pdf
  default: 'pdf'
  help: 'Output format for bamqc'
bamqc_additional_options:
  type: 'String'
  required: false
  allow_empty: true
  default: ''
  help: 'Additional arguments for bamqc command'
base_resource_update:
  type: 'ResourceUpdateNamespace'
  required: false
  help: 'User-defined modifications for adjusting base resource allocations for processes'
  elements:
    memory:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of memory updates'
    cpus:
      type: 'ResourceUpdateList'
      required: false
      help: 'List of CPU updates'
input:
  type: 'InputNamespace'
  required: true
  help: 'Input to process'
  elements:
    BAM:
      type: 'InputBAMNamespace'
      required: true
      help: 'BAM input specifications'
      elements:
        normal:
          type: 'MapList'
          required: false
          help: 'Normal sample input specifications'
          elements:
            path:
              type: 'Path'
              mode: 'r'
              required: true
              help: 'Absolute path to normal sample BAM files'
            read_length:
              type: 'Integer'
              required: false
              help: 'Length of the reads in the BAM file'
        tumor:
          type: 'MapList'
          required: false
          help: 'Tumor sample input specifications'
          elements:
            path:
              type: 'Path'
              mode: 'r'
              required: true
              help: 'Absolute path to tumor sample BAM files'
            read_length:
              type: 'Integer'
              required: false
              help: 'Length of the reads in the BAM file'
